manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: q123321a
      url-base: https://github.com/q123321a
  projects:
    - name: zmkfirmware
      remote: q123321a
      revision: main
      import: app/west.yml
  self:
    path: config
